mode = "dark"

accent = "#7daea3"
selection = "#404040"
muted = "#595959"

background = "#1d2021"
dark_background = "#191b1c"
darker_background = "#141617"
lighter_background = "#292929"

foreground = "#ebdbb2"
dark_foreground = "#928374"
light_foreground = "#d5c4a1"
bright_foreground = "#ebdbb2"

red = "#ea6962"
yellow = "#d8a657"
orange = "#e78a4e"
green = "#a9b665"
cyan = "#89b482"
blue = "#7daea3"
magenta = "#d3869b"
brown = "#70432e"

bright_red = "#ea6962"
bright_yellow = "#d8a657"
bright_green = "#a9b665"
bright_cyan = "#89b482"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
