mode = "dark"

# Source: https://github.com/sainnhe/sonokai
# Revision: b023c5280b16fe2366f5e779d8d2756b3e5ee9c3

# Omarchy compatibility projection.
accent = "#72cce8"
selection = "#3d4455"
muted = "#424b5b"
background = "#2a2f38"
dark_background = "#24272e"
darker_background = "#181a1c"
lighter_background = "#333846"
foreground = "#e1e3e4"
dark_foreground = "#5a6477"
light_foreground = "#828a9a"
bright_foreground = "#e1e3e4"
red = "#ff6578"
yellow = "#eacb64"
orange = "#f69c5e"
green = "#9dd274"
cyan = "#f69c5e"
blue = "#72cce8"
magenta = "#ba9cf3"
brown = "#f69c5e"
bright_red = "#ff6578"
bright_yellow = "#eacb64"
bright_green = "#9dd274"
bright_cyan = "#f69c5e"
bright_blue = "#72cce8"
bright_magenta = "#ba9cf3"
