mode = "dark"

# Source: https://github.com/rebelot/kanagawa.nvim
# Revision: bb85e4bfc8d89b0e62c8fa53ccdd13d12e2f77b3

# Omarchy compatibility projection.
accent = "#8ba4b0"
selection = "#223249"
muted = "#625e5a"
background = "#181616"
dark_background = "#1d1c19"
darker_background = "#12120f"
lighter_background = "#282727"
foreground = "#c5c9c5"
dark_foreground = "#737c73"
light_foreground = "#c8c093"
bright_foreground = "#c5c9c5"
red = "#c4746e"
yellow = "#c4b28a"
orange = "#c4746e"
green = "#8a9a7b"
cyan = "#8ea4a2"
blue = "#8ba4b0"
magenta = "#a292a3"
brown = "#b6927b"
bright_red = "#e46876"
bright_yellow = "#e6c384"
bright_green = "#87a987"
bright_cyan = "#7aa89f"
bright_blue = "#7fb4ca"
bright_magenta = "#938aa9"
