mode = "dark"

# Source: https://github.com/folke/tokyonight.nvim
# Revision: cdc07ac78467a233fd62c493de29a17e0cf2b2b6

# Omarchy compatibility projection.
accent = "#82aaff"
selection = "#2d3f76"
muted = "#394b70"
background = "#222436"
dark_background = "#1e2030"
darker_background = "#191b29"
lighter_background = "#2f334d"
foreground = "#c8d3f5"
dark_foreground = "#636da6"
light_foreground = "#828bb8"
bright_foreground = "#c8d3f5"
red = "#ff757f"
yellow = "#ffc777"
orange = "#ff966c"
green = "#c3e88d"
cyan = "#86e1fc"
blue = "#82aaff"
magenta = "#c099ff"
brown = "#ff966c"
bright_red = "#ff8d94"
bright_yellow = "#ffd8ab"
bright_green = "#c7fb6d"
bright_cyan = "#b2ebff"
bright_blue = "#9ab8ff"
bright_magenta = "#caabff"
