mode = "dark"

# Source: https://github.com/folke/tokyonight.nvim
# Revision: cdc07ac78467a233fd62c493de29a17e0cf2b2b6

# Omarchy compatibility projection.
accent = "#7aa2f7"
selection = "#283457"
muted = "#394b70"
background = "#1a1b26"
dark_background = "#16161e"
darker_background = "#0c0e14"
lighter_background = "#292e42"
foreground = "#c0caf5"
dark_foreground = "#565f89"
light_foreground = "#a9b1d6"
bright_foreground = "#c0caf5"
red = "#f7768e"
yellow = "#e0af68"
orange = "#ff9e64"
green = "#9ece6a"
cyan = "#7dcfff"
blue = "#7aa2f7"
magenta = "#bb9af7"
brown = "#ff9e64"
bright_red = "#ff899d"
bright_yellow = "#faba4a"
bright_green = "#9fe044"
bright_cyan = "#a4daff"
bright_blue = "#8db0ff"
bright_magenta = "#c7a9ff"
