mode = "light"

# Source: https://github.com/folke/tokyonight.nvim
# Revision: cdc07ac78467a233fd62c493de29a17e0cf2b2b6

# Omarchy compatibility projection.
accent = "#2e7de9"
selection = "#b7c1e3"
muted = "#92a6d5"
background = "#e1e2e7"
dark_background = "#d0d5e3"
darker_background = "#c1c9df"
lighter_background = "#c4c8da"
foreground = "#3760bf"
dark_foreground = "#848cb5"
light_foreground = "#6172b0"
bright_foreground = "#3760bf"
red = "#f52a65"
yellow = "#8c6c3e"
orange = "#b15c00"
green = "#587539"
cyan = "#007197"
blue = "#2e7de9"
magenta = "#9854f1"
brown = "#b15c00"
bright_red = "#ff4774"
bright_yellow = "#a27629"
bright_green = "#5c8524"
bright_cyan = "#007ea8"
bright_blue = "#358aff"
bright_magenta = "#a463ff"
