mode = "light"

# Source: https://github.com/ayu-theme/ayu-colors
# Revision: e3f44fdf2a1c83e3f183d4e8acd40c6a452dcb1c

# Omarchy compatibility projection.
accent = "#f29718"
selection = "#d7e4f6"
muted = "#c5c5c8"
background = "#fcfcfc"
dark_background = "#f8f9fa"
darker_background = "#ebeef0"
lighter_background = "#fafafa"
foreground = "#5c6166"
dark_foreground = "#adaeb1"
light_foreground = "#828e9f"
bright_foreground = "#5c6166"
red = "#f07171"
yellow = "#eba400"
orange = "#f2a191"
green = "#86b300"
cyan = "#4cbf99"
blue = "#22a4e6"
magenta = "#a37acc"
brown = "#e59645"
bright_red = "#f07171"
bright_yellow = "#eba400"
bright_green = "#86b300"
bright_cyan = "#4cbf99"
bright_blue = "#22a4e6"
bright_magenta = "#a37acc"
