add_newline = false

command_timeout = 3000

format = """
$directory\
$git_branch \
$git_commit\
$git_state
$character\
"""

[character]
success_symbol = " [➜](green)"

[directory]
format = '[   $path]($style) [$read_only]($read_only_style) '
read_only = "󰌾"
style = "blue"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
style = 'purple'

[git_commit]
style = "green"

[git_state]
style = "yellow"

[docker_context]
disabled = true

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'yellow'
symbol = " "
