add_newline = false

command_timeout = 3000

# A minimal left prompt
format = """
$directory\
$git_branch \
$git_commit\
$git_state\
$fill\
$character\
"""

[fill]
symbol = " "

[character]
vicmd_symbol = " [\\[N\\] ➜](blue)"
success_symbol = " [\\[I\\] ➜](green)"

[directory]
format = '[   $path]($style) [$read_only]($read_only_style) '
read_only = "󰌾"
style = "surface2"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
style = 'mauve'

[git_commit]
style = "green"

[git_state]
style = "yellow"

[docker_context]
disabled = true

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'yellow'
symbol = " "
