config-version = 2
start-at-login = true
auto-reload-config = true
after-startup-command = ["exec-and-forget borders"]

accordion-padding = 24
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
# automatically-unhide-macos-hidden-apps = true
# enable-normalization-opposite-orientation-for-nested-containers = false

gaps.inner.horizontal = 8
gaps.inner.vertical = 8
gaps.outer.left = 8
gaps.outer.bottom = 8
gaps.outer.top = 6
gaps.outer.right = 8

# Named workspaces (see keybindings below):
#   code
#   browser
#   chat
#   docs
#   design

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace code'

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace browser'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace browser'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace docs'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[workspace-to-monitor-force-assignment]
chat = ['secondary', '^DELL U2722D \(1\)$']

[mode.main.binding]

alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"

alt-shift-h = "move --boundaries-action stop left"
alt-shift-j = "move --boundaries-action stop down"
alt-shift-k = "move --boundaries-action stop up"
alt-shift-l = "move --boundaries-action stop right"

alt-ctrl-shift-f = "layout floating tiling"
alt-ctrl-shift-r = "layout horizontal vertical"
alt-ctrl-shift-s = "layout accordion tiles"

alt-ctrl-shift-h = 'join-with left'
alt-ctrl-shift-j = 'join-with down'
alt-ctrl-shift-k = 'join-with up'
alt-ctrl-shift-l = 'join-with right'

alt-ctrl-b = "balance-sizes"
alt-ctrl-h = "resize width -50"
alt-ctrl-j = "resize height +50"
alt-ctrl-k = "resize height -50"
alt-ctrl-l = "resize width +50"

alt-c = "workspace code"
alt-b = "workspace browser"
alt-s = "workspace chat"
alt-d = "workspace docs"
alt-f = "workspace design"
alt-tab = "workspace-back-and-forth"
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-c = "move-node-to-workspace code"
alt-shift-b = "move-node-to-workspace browser"
alt-shift-s = "move-node-to-workspace chat"
alt-shift-d = "move-node-to-workspace docs"
alt-shift-f = "move-node-to-workspace design"

alt-m = 'exec-and-forget $HOME/.local/bin/aerospace-toggle-app com.spotify.client'
alt-i = 'exec-and-forget $HOME/.local/bin/aerospace-toggle-app com.apple.finder'
