mode = "dark"

# Source: https://github.com/sainnhe/sonokai
# Revision: b023c5280b16fe2366f5e779d8d2756b3e5ee9c3

# Omarchy compatibility projection.
accent = "#76cce0"
selection = "#3b3e48"
muted = "#414550"
background = "#2c2e34"
dark_background = "#222327"
darker_background = "#181819"
lighter_background = "#33353f"
foreground = "#e2e2e3"
dark_foreground = "#595f6f"
light_foreground = "#7f8490"
bright_foreground = "#e2e2e3"
red = "#fc5d7c"
yellow = "#e7c664"
orange = "#f39660"
green = "#9ed072"
cyan = "#f39660"
blue = "#76cce0"
magenta = "#b39df3"
brown = "#f39660"
bright_red = "#fc5d7c"
bright_yellow = "#e7c664"
bright_green = "#9ed072"
bright_cyan = "#f39660"
bright_blue = "#76cce0"
bright_magenta = "#b39df3"
