mode = "light"

# Source: https://github.com/rebelot/kanagawa.nvim
# Revision: bb85e4bfc8d89b0e62c8fa53ccdd13d12e2f77b3

# Omarchy compatibility projection.
accent = "#4d699b"
selection = "#c9cbd1"
muted = "#8a8980"
background = "#f2ecbc"
dark_background = "#e5ddb0"
darker_background = "#dcd5ac"
lighter_background = "#e7dba0"
foreground = "#545464"
dark_foreground = "#8a8980"
light_foreground = "#43436c"
bright_foreground = "#545464"
red = "#c84053"
yellow = "#77713f"
orange = "#836f4a"
green = "#6f894e"
cyan = "#597b75"
blue = "#4d699b"
magenta = "#b35b79"
brown = "#cc6d00"
bright_red = "#d7474b"
bright_yellow = "#836f4a"
bright_green = "#6e915f"
bright_cyan = "#5e857a"
bright_blue = "#6693bf"
bright_magenta = "#624c83"
