mode = "dark"

# Source: https://github.com/cocopon/iceberg.vim
# Revision: 23835d5ed696436f716cbfdb56a93a7850fe3b18

# Omarchy compatibility projection.
accent = "#84a0c6"
selection = "#272c42"
muted = "#6b7089"
background = "#161821"
dark_background = "#1e2132"
darker_background = "#1e2132"
lighter_background = "#272c42"
foreground = "#c6c8d1"
dark_foreground = "#6b7089"
light_foreground = "#6b7089"
bright_foreground = "#c6c8d1"
red = "#e27878"
yellow = "#e2a478"
orange = "#e2a478"
green = "#b4be82"
cyan = "#89b8c2"
blue = "#84a0c6"
magenta = "#a093c7"
brown = "#e2a478"
bright_red = "#e98989"
bright_yellow = "#e9b189"
bright_green = "#c0ca8e"
bright_cyan = "#95c4ce"
bright_blue = "#91acd1"
bright_magenta = "#ada0d3"
