mode = "light"

# Source: https://github.com/cocopon/iceberg.vim
# Revision: 23835d5ed696436f716cbfdb56a93a7850fe3b18

# Omarchy compatibility projection.
accent = "#2d539e"
selection = "#c9cdd7"
muted = "#8389a3"
background = "#e8e9ec"
dark_background = "#dcdfe7"
darker_background = "#dcdfe7"
lighter_background = "#cad0de"
foreground = "#33374c"
dark_foreground = "#8389a3"
light_foreground = "#8389a3"
bright_foreground = "#33374c"
red = "#cc517a"
yellow = "#c57339"
orange = "#c57339"
green = "#668e3d"
cyan = "#3f83a6"
blue = "#2d539e"
magenta = "#7759b4"
brown = "#c57339"
bright_red = "#cc3768"
bright_yellow = "#b6662d"
bright_green = "#598030"
bright_cyan = "#327698"
bright_blue = "#22478e"
bright_magenta = "#6845ad"
