mode = "dark"

# Source: https://github.com/sainnhe/sonokai
# Revision: b023c5280b16fe2366f5e779d8d2756b3e5ee9c3

# Omarchy compatibility projection.
accent = "#6dcae8"
selection = "#393e53"
muted = "#3f445b"
background = "#2b2d3a"
dark_background = "#252630"
darker_background = "#181a1c"
lighter_background = "#333648"
foreground = "#e1e3e4"
dark_foreground = "#5a5e7a"
light_foreground = "#7e8294"
bright_foreground = "#e1e3e4"
red = "#fb617e"
yellow = "#edc763"
orange = "#f89860"
green = "#9ed06c"
cyan = "#f89860"
blue = "#6dcae8"
magenta = "#bb97ee"
brown = "#f89860"
bright_red = "#fb617e"
bright_yellow = "#edc763"
bright_green = "#9ed06c"
bright_cyan = "#f89860"
bright_blue = "#6dcae8"
bright_magenta = "#bb97ee"
