mode = "dark"

# Source: https://github.com/sainnhe/sonokai
# Revision: b023c5280b16fe2366f5e779d8d2756b3e5ee9c3

# Omarchy compatibility projection.
accent = "#81d0c9"
selection = "#49403c"
muted = "#4e433f"
background = "#312c2b"
dark_background = "#242120"
darker_background = "#1f1e1c"
lighter_background = "#393230"
foreground = "#e4e3e1"
dark_foreground = "#6a5e59"
light_foreground = "#90817b"
bright_foreground = "#e4e3e1"
red = "#f86882"
yellow = "#f0c66f"
orange = "#f08d71"
green = "#a6cd77"
cyan = "#f08d71"
blue = "#81d0c9"
magenta = "#9fa0e1"
brown = "#f08d71"
bright_red = "#f86882"
bright_yellow = "#f0c66f"
bright_green = "#a6cd77"
bright_cyan = "#f08d71"
bright_blue = "#81d0c9"
bright_magenta = "#9fa0e1"
