return {
    mode = '{{ mode }}',
    colors = {
        rosewater = '{{ accent_soft }}',
        flamingo = '{{ accent_warm }}',
        red = '{{ error }}',
        maroon = '{{ error_muted }}',
        pink = '{{ syntax_attribute }}',
        mauve = '{{ syntax_constant }}',
        peach = '{{ syntax_operator }}',
        yellow = '{{ warning }}',
        green = '{{ success }}',
        teal = '{{ syntax_string }}',
        sky = '{{ info_bright }}',
        sapphire = '{{ info_muted }}',
        blue = '{{ accent }}',
        lavender = '{{ info_soft }}',
        text = '{{ foreground }}',
        subtext1 = '{{ foreground_subtle }}',
        subtext0 = '{{ foreground_muted }}',
        overlay2 = '{{ overlay_tertiary }}',
        overlay1 = '{{ overlay_secondary }}',
        overlay0 = '{{ overlay }}',
        surface2 = '{{ surface_tertiary }}',
        surface1 = '{{ surface_secondary }}',
        surface0 = '{{ surface }}',
        base = '{{ background }}',
        mantle = '{{ background_secondary }}',
        crust = '{{ background_tertiary }}',
    },
}
