return {
    mode = '{{ mode }}',
    colors = {
        rosewater = '{{ orange }}',
        flamingo = '{{ red }}',
        red = '{{ red }}',
        maroon = '{{ bright_red }}',
        pink = '{{ bright_magenta }}',
        mauve = '{{ magenta }}',
        peach = '{{ orange }}',
        yellow = '{{ yellow }}',
        green = '{{ green }}',
        teal = '{{ cyan }}',
        sky = '{{ bright_cyan }}',
        sapphire = '{{ cyan }}',
        blue = '{{ blue }}',
        lavender = '{{ bright_blue }}',
        text = '{{ foreground }}',
        subtext1 = '{{ light_foreground }}',
        subtext0 = '{{ dark_foreground }}',
        overlay2 = '{{ muted }}',
        overlay1 = '{{ muted }}',
        overlay0 = '{{ muted }}',
        surface2 = '{{ selection }}',
        surface1 = '{{ lighter_background }}',
        surface0 = '{{ lighter_background }}',
        base = '{{ background }}',
        mantle = '{{ dark_background }}',
        crust = '{{ darker_background }}',
    },
}
