{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "dotfiles",
  "colors": {
    "accent": "{{ accent }}",
    "border": "{{ blue }}",
    "borderAccent": "{{ accent }}",
    "borderMuted": "{{ muted }}",
    "success": "{{ green }}",
    "error": "{{ red }}",
    "warning": "{{ yellow }}",
    "muted": "{{ dark_foreground }}",
    "dim": "{{ muted }}",
    "text": "{{ foreground }}",
    "thinkingText": "{{ dark_foreground }}",
    "selectedBg": "{{ selection }}",
    "scrollbarThumb": "{{ selection }}",
    "searchMatchBg": "{{ selection }}",
    "searchMatchText": "{{ bright_foreground }}",
    "userMessageBg": "{{ lighter_background }}",
    "userMessageText": "{{ foreground }}",
    "customMessageBg": "{{ dark_background }}",
    "customMessageText": "{{ foreground }}",
    "customMessageLabel": "{{ magenta }}",
    "toolPendingBg": "{{ darker_background }}",
    "toolSuccessBg": "{{ dark_background }}",
    "toolErrorBg": "{{ dark_background }}",
    "toolTitle": "{{ foreground }}",
    "toolOutput": "{{ dark_foreground }}",
    "mdHeading": "{{ yellow }}",
    "mdLink": "{{ blue }}",
    "mdLinkUrl": "{{ muted }}",
    "mdCode": "{{ cyan }}",
    "mdCodeBlock": "{{ green }}",
    "mdCodeBlockBorder": "{{ muted }}",
    "mdQuote": "{{ dark_foreground }}",
    "mdQuoteBorder": "{{ muted }}",
    "mdHr": "{{ muted }}",
    "mdListBullet": "{{ accent }}",
    "toolDiffAdded": "{{ green }}",
    "toolDiffRemoved": "{{ red }}",
    "toolDiffContext": "{{ dark_foreground }}",
    "syntaxComment": "{{ muted }}",
    "syntaxKeyword": "{{ magenta }}",
    "syntaxFunction": "{{ blue }}",
    "syntaxVariable": "{{ foreground }}",
    "syntaxString": "{{ green }}",
    "syntaxNumber": "{{ orange }}",
    "syntaxType": "{{ cyan }}",
    "syntaxOperator": "{{ accent }}",
    "syntaxPunctuation": "{{ dark_foreground }}",
    "thinkingOff": "{{ muted }}",
    "thinkingMinimal": "{{ dark_foreground }}",
    "thinkingLow": "{{ blue }}",
    "thinkingMedium": "{{ cyan }}",
    "thinkingHigh": "{{ magenta }}",
    "thinkingXhigh": "{{ bright_magenta }}",
    "thinkingMax": "{{ bright_red }}",
    "bashMode": "{{ green }}"
  },
  "export": {
    "pageBg": "{{ darker_background }}",
    "cardBg": "{{ background }}",
    "infoBg": "{{ dark_background }}"
  }
}
