{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "dotfiles",
  "colors": {
    "accent": "{{ accent }}",
    "border": "{{ accent }}",
    "borderAccent": "{{ accent }}",
    "borderMuted": "{{ overlay }}",
    "success": "{{ success }}",
    "error": "{{ error }}",
    "warning": "{{ warning }}",
    "muted": "{{ foreground_muted }}",
    "dim": "{{ overlay }}",
    "text": "{{ foreground }}",
    "thinkingText": "{{ foreground_muted }}",
    "selectedBg": "{{ selection }}",
    "scrollbarThumb": "{{ selection }}",
    "searchMatchBg": "{{ selection }}",
    "searchMatchText": "{{ foreground }}",
    "userMessageBg": "{{ surface }}",
    "userMessageText": "{{ foreground }}",
    "customMessageBg": "{{ background_secondary }}",
    "customMessageText": "{{ foreground }}",
    "customMessageLabel": "{{ syntax_constant }}",
    "toolPendingBg": "{{ background_tertiary }}",
    "toolSuccessBg": "{{ background_secondary }}",
    "toolErrorBg": "{{ background_secondary }}",
    "toolTitle": "{{ foreground }}",
    "toolOutput": "{{ foreground_muted }}",
    "mdHeading": "{{ warning }}",
    "mdLink": "{{ accent }}",
    "mdLinkUrl": "{{ overlay }}",
    "mdCode": "{{ syntax_string }}",
    "mdCodeBlock": "{{ success }}",
    "mdCodeBlockBorder": "{{ overlay }}",
    "mdQuote": "{{ foreground_muted }}",
    "mdQuoteBorder": "{{ overlay }}",
    "mdHr": "{{ overlay }}",
    "mdListBullet": "{{ accent }}",
    "toolDiffAdded": "{{ success }}",
    "toolDiffRemoved": "{{ error }}",
    "toolDiffContext": "{{ foreground_muted }}",
    "syntaxComment": "{{ overlay }}",
    "syntaxKeyword": "{{ syntax_constant }}",
    "syntaxFunction": "{{ accent }}",
    "syntaxVariable": "{{ foreground }}",
    "syntaxString": "{{ syntax_string }}",
    "syntaxNumber": "{{ syntax_operator }}",
    "syntaxType": "{{ info_bright }}",
    "syntaxOperator": "{{ syntax_operator }}",
    "syntaxPunctuation": "{{ foreground_muted }}",
    "thinkingOff": "{{ overlay }}",
    "thinkingMinimal": "{{ foreground_muted }}",
    "thinkingLow": "{{ accent }}",
    "thinkingMedium": "{{ info_bright }}",
    "thinkingHigh": "{{ syntax_constant }}",
    "thinkingXhigh": "{{ syntax_attribute }}",
    "thinkingMax": "{{ error }}",
    "bashMode": "{{ success }}"
  },
  "export": {
    "pageBg": "{{ background_tertiary }}",
    "cardBg": "{{ background }}",
    "infoBg": "{{ background_secondary }}"
  }
}
