mode = "dark"

# Source: https://github.com/sainnhe/sonokai
# Revision: b023c5280b16fe2366f5e779d8d2756b3e5ee9c3

# Omarchy compatibility projection.
accent = "#7accd7"
selection = "#423f46"
muted = "#49464e"
background = "#2d2a2e"
dark_background = "#211f21"
darker_background = "#1a181a"
lighter_background = "#37343a"
foreground = "#e3e1e4"
dark_foreground = "#605d68"
light_foreground = "#848089"
bright_foreground = "#e3e1e4"
red = "#f85e84"
yellow = "#e5c463"
orange = "#ef9062"
green = "#9ecd6f"
cyan = "#ef9062"
blue = "#7accd7"
magenta = "#ab9df2"
brown = "#ef9062"
bright_red = "#f85e84"
bright_yellow = "#e5c463"
bright_green = "#9ecd6f"
bright_cyan = "#ef9062"
bright_blue = "#7accd7"
bright_magenta = "#ab9df2"
