[theme]
name = "gruvbox"

[theme.custom]
sidebar_bg = "#191b1c"
panel_bg = "reset"
accent = "#7daea3"
red = "#d3869b"
green = "#a9b665"
blue = "#7daea3"
yellow = "#d8a657"

[terminal]
new_cwd = "follow"

[keys]
prefix = "ctrl+a"
reload_config = "prefix+r"

workspace_picker = ["prefix+w"]
rename_workspace = ["prefix+shift+w"]

new_tab = "prefix+t"
move_tab_previous = "ctrl+shift+left"
move_tab_next = "ctrl+shift+right"
next_tab = ["prefix+n", "prefix+ctrl+n"]
previous_tab = ["prefix+p", "prefix+ctrl+p"]

# focus_pane_left = "prefix+left"
# focus_pane_down = "prefix+down"
# focus_pane_up = "prefix+up"
# focus_pane_right = "prefix+right"

split_vertical = ["prefix+%", "prefix+v"]
split_horizontal = ["prefix+\"", "prefix+s"]
close_pane = "prefix+x"

navigate_workspace_up = ["k", "ctrl+p"]
navigate_workspace_down = ["j", "ctrl+n"]

settings = "prefix+,"

[[keys.command]]
key = "prefix+c"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "80%"
height = "80%"

[[keys.command]]
key = "ctrl+h"
type = "shell"
command = "herdr-nvim-navigator left"
description = "navigate pane left"

[[keys.command]]
key = "ctrl+j"
type = "shell"
command = "herdr-nvim-navigator down"
description = "navigate pane down"

[[keys.command]]
key = "ctrl+k"
type = "shell"
command = "herdr-nvim-navigator up"
description = "navigate pane up"

[[keys.command]]
key = "ctrl+l"
type = "shell"
command = "herdr-nvim-navigator right"
description = "navigate pane right"

[[keys.command]]
key = "ctrl+shift+h"
type = "shell"
command = "herdr-nvim-navigator resize left"
description = "resize pane left"

[[keys.command]]
key = "ctrl+shift+j"
type = "shell"
command = "herdr-nvim-navigator resize down"
description = "resize pane down"

[[keys.command]]
key = "ctrl+shift+k"
type = "shell"
command = "herdr-nvim-navigator resize up"
description = "resize pane up"

[[keys.command]]
key = "ctrl+shift+l"
type = "shell"
command = "herdr-nvim-navigator resize right"
description = "resize pane right"

[ui]
mouse_capture = true
copy_on_select = false
pane_borders = true
pane_outer_borders = false
pane_scrollbars = false
pane_gaps = false
tab_bar_position = "top"
tab_bar_right = [{ type = "zoom" }]
window_title = "{hostname}:{tab}"
status_indicators = "dots"

[advanced]
scrollback_limit_bytes = 50000000
